### DISCUSSION TITLE
Is there a way to output an image with higher quality when using it in a background CSS rule?

### DISCUSSION THREAD

**Discussion by csalmeida** [dompdf/dompdf#3148] [Q&A] [answered]
Hi all,

I got this package set up to generate a custom PDF.
One of the requirements is that the text needs to be placed in certain parts of an image and to achieve this I've set a   `background-image` which does render the image.

However, for some reason, the image is pixelated when the PDF is generated. Is there a way to get the image to look sharp?

The CSS I've used to render the image in the background is:

```css
body {
    font-family: Arial, sans-serif;
    background-image: url(/** path here **/);
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    width:100%;
    height:100%;
}
```

Would be grateful for any advice on how to overcome this.
Thank you 🙏
