### DISCUSSION TITLE
Styling based on odd/even page position

### DISCUSSION THREAD

**Discussion by ghost** [dompdf/dompdf#3205] [Q&A] [answered]
Is it possible to style an element based on whether it appears on an odd or even page with DomPDF?

We would like to implement a simple footer for a two-sided print where the page number is always on the outside of the document. Which in my mind would only require a single `float` or `display`-CSS property to be changed depending on the page. 

```css
.page_title:before {
  content: 'Document Title';
}

.page_number:before {
  content: counter(page);
}

.node.footer {
  position: fixed;
  inset: auto 0mm -27.5mm 0mm;

  display: block;

  height: 17.5mm;
  text-align: end;
}

.node.footer > .footer-start,
.node.footer > .footer-end {
  display: inline-block;
}

.node.footer > .footer-end {
  float: right;
}

/* --- */
:host([page-odd]) .node.footer > .footer-start {
  display: none;
}
:host([page-even]) .node.footer > .footer-end {
  display: none;
}
/* --- */
```

```html
<div class="node footer">
  <div class="footer-start">
    <div class="type caption">
      <span class="page_number"></span>
      <span style="margin: 0mm 2mm;">—</span>
      <span class="page_title"></span>
    </div>
  </div>
  <div class="footer-end">
    <div class="type caption">
      <span class="page_number"></span>
    </div>
  </div>
</div>
```

![Untitled-2022-11-15-0850](https://github.com/dompdf/dompdf/assets/117671930/fd216494-3886-4a8e-ad54-94948ddae62b)

---

#3178 is similar to this but doesn't feel like a solution, as it would not work with auto page breaks. Is there any way to do this programmatically?
