### ISSUE TITLE
cannot generate multiple pdf files

### ISSUE THREAD

**Issue by garak** [dompdf/dompdf#1056]
I found that I cannot generate multiple pdf file with a single Dompdf instance.
So, I cannot inject Dompdf as a dependency of my class, and instead I'm forced to create one instance of Dompdf for each pdf file I have to create.
This is bad, since I cannot decouple my class from Dompdf, violating the inversion of control pattern.

For the record, trying to generate a second pdf with the same instance of Dompdf is resulting in the following exception (while the same file, generated with a new instance, is fine):
```
No block-level parent found. Not good. 
```
thrown in ``vendor/dompdf/dompdf/src/Positioner/Inline.php`` at line 48

I'm using dompdf v0.7.0-beta2

**Comment by bsweeney** [comment]
This is a known problem, though I can't recall if there's already an issue associated with it.

**Comment by sh4ka** [comment]
I'm having this exact bug using this in a console command in laravel 5.1.

**Comment by Pankaj-D** [comment]
Does anybody have the solution for this issue?

**Comment by bsweeney** [comment]
We'll patch this up in the next release, in the meantime just `unset` your dompdf variable and re-instantiate before each subsequent use.

FYI, also bad is calling both the `output` and `stream` methods from the same instance.

**Comment by Soullivaneuh** [comment]
> We'll patch this up in the next release, in the meantime just unset your dompdf variable and re-instantiate before each subsequent use.

Well, my instance is a Symfony service:

```yaml
dompdf:
    class: Dompdf\Dompdf
    public: false
    calls:
        - [ 'set_host', [ '%router.request_context.host%' ] ]
        - [ 'set_protocol', [ '%router.request_context.scheme%://' ] ]
        - [ 'set_option', [ 'font_dir', '%kernel.cache_dir%/dompdf/fonts' ] ]
        - [ 'set_option', [ 'log_output_file', '%kernel.logs_dir%/dompdf.html' ] ]
        - [ 'set_option', [ 'enable_remote', true ] ]
```

Any another workaround @bsweeney ?
