### ISSUE TITLE
Checkbox is not displayed

### ISSUE THREAD

**Issue by TobiGr** [dompdf/dompdf#1121]
Hello,
I have a problem creating checkboxes. HTML code like this returns questionmarks:
`<input type="checkbox">`
`<input type="checkbox" checked>`
`<input type="checkbox" checked="checked">`
`<input type="checkbox" selected=\"selected\" >`
Is there any way to display a checkbox correctly?

**Comment by bsweeney** [comment]
It looks like the styling on the checkbox element isn't quite right. A "?" will show in place of the checkbox if your stylesheet applies a font to that element that does not include the [ballot box glyph](https://en.wikipedia.org/wiki/Ballot_box#Unicode).

You can fix the rendering by adding the following to your stylesheet:

```css
input[type=checkbox]:before { font-family: DejaVu Sans; }
```

Also, you might want to also add the following to prevent the checkbox element from taking up an entire line (see #1031):

```css
input[type=checkbox] { display: inline; }
```
