### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by ghost** [dompdf/dompdf#1427]
We have two servers that our software is deployed to at the moment. On produces the PDF's correctly, the other seems to ignore alot of the CSS.

I have attached both the working and broken PDF's produced by the same code.

[broken.pdf](https://github.com/dompdf/dompdf/files/922125/broken.pdf)
[working.pdf](https://github.com/dompdf/dompdf/files/922126/working.pdf)

Any ideas what could be causing this?

**Comment by bsweeney** [comment]
Is the CSS included in the document or referenced in an external stylesheet. More than one stylesheet?

**Comment by McGreeb** [comment]
a couple of external style sheets

**Comment by bsweeney** [comment]
The reference to one may not be accurate for one of the servers, unless they're exact mirrors. How are you loading the document into dompdf? How are you referencing the external stylesheets?

**Comment by McGreeb** [comment]
I am doing this from within Laravel, If I bypass dompdf and load the view directly in HTML it looks fine.

     ```
   if($producepdf == true){
            
            $filepath = app_path().'/TestFiles/';
            $tempfilename = hash('sha1', Auth::user()->email)."-".hash('sha1', date(DATE_RFC2822)).'.pdf';

            $file = $filepath . $tempfilename;
            
            $pdf = PDF::loadView('pdf.Reports.ProfitLoss', compact('enddate', 'companyinfo', 'companyaddress', 'incometotal', 'profitloss' , 'sales', 'expences' , 'expencestotal'))->setPaper('A4', 'portrait')->save($file);

            return response()->file($file)->deleteFileAfterSend(true);
            
        }else{
            
            return View::make('pdf.Reports.ProfitLoss')
                ->with('enddate', $enddate)    
                ->with('companyinfo', $companyinfo)
                ->with('companyaddress', $companyaddress)
                ->with('incometotal', $incometotal)
                ->with('profitloss', $profitloss)
                ->with('sales', $sales)
                ->with('expences', $expences)
                ->with('expencestotal', $expencestotal);
            
        }
```
when i set $producepdf to false I get perfect looking html out.

styling is included as bellow

```
    <link rel="stylesheet" href="{{ url('/includes/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url('/includes/pdf.css') }}">
```

**Comment by bsweeney** [comment]
Perhaps dompdf is having trouble reading the minimzed version of the bootstrap stylesheet on the second server?

You might try loading a fresh copy of dompdf on the server where it's not rendering correctly.

**Comment by caliburn82** [comment]
I get problems as well but mainly when using CSS variables on margin or padding.

```css
:root {
    --spacing: 20px;
    --size: 300px;
    --grey: #888888;
}

.container {
    background: var(--grey-d);
    font-size: var(--spacing);
    margin: var(--spacing) 0; /* Errors: A non-numeric value encountered */
    padding: var(--spacing); /* Error: Box property calculation requires containing block width */
    width: var(--size);
}
```
