### ISSUE TITLE
Unable to display UTF-8 (Chinese) with English characters 

### ISSUE THREAD

**Issue by asika32764** [dompdf/dompdf#1508]
I follow [UnicodeHowTo](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo) to generate a DroidSansFallback.ttf font and use this HTML to create PDF:

```php
<?php
require_once __DIR__ . "/vendor/autoload.php";

ob_start();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Document</title>
    <style>
    body {
        font-family: droidsansfallback, sans-serif;
    }
    </style>
</head>
<body>
    中文 / English
</body>
</html>
<?php
$content = ob_get_clean();

$dompdf = new \Dompdf\Dompdf();
$dompdf->loadHtml($content);
$dompdf->render();

header('Content-Type: application/pdf; charset=utf-8');
header('Content-disposition: inline; filename="' .  $no . '.pdf"', true);

echo $dompdf->output();

```

Before applying the font-family, Dompdf can display English but unable for Chinese:

![p-2017-08-11-001](https://user-images.githubusercontent.com/1639206/29181346-606ae966-7e2d-11e7-974d-8bc559ad4677.jpg)

After applied the `droidsansfallback` font, Chinese can correctly display but English not:

![p-2017-08-11-002](https://user-images.githubusercontent.com/1639206/29181381-80141b02-7e2d-11e7-8f1a-ee9202c633bc.jpg)

I can make sure this `DroidSansFallback.ttf` did not lack Ascii character because it can still print a little part of English and numbers:

![p-2017-08-11-003](https://user-images.githubusercontent.com/1639206/29181446-c8700e60-7e2d-11e7-96bc-5883f6cb8cfb.jpg)

And I tried use other Google fonts with:

```css
@font-face {
      font-family: 'cwTeXKai';
      font-style: normal;
      font-weight: 500;
      src: url(http://fonts.gstatic.com/ea/cwtexkai/v3/cwTeXKai-zhonly.ttf) format('truetype');
    }

    body {
        font-family: cwTeXKai, sans-serif;
    }
```

But still not work:

![p-2017-08-11-004](https://user-images.githubusercontent.com/1639206/29181573-3d4b7864-7e2e-11e7-97cc-5eb2ed69a1bd.jpg)

This problem exists on 0.8.0 and 0.7.0.

Can anyone advise me how to solve this problem?
