### ISSUE TITLE
[0.8.2] margin-top on elements on multiple pages

### ISSUE THREAD

**Issue by Spreeuw** [dompdf/dompdf#1613]
This worked fine in 0.8.0 but seems to have been broken in 0.8.2.
The margin-top is only respected on the first page, but on subsequent pages it is ignored:
HTML:
``` html
<div class='first-element'>Some text</div>
<div class="page-break"></div>
<div class='first-element'>Some text</div>
<div class="page-break"></div>
<div class='first-element'>Some text</div>
```
CSS:
``` css
.first-element {
	margin-top: 50mm;
}
.page-break {
	page-break-before: always;
}
```
