### ISSUE TITLE
Entire list is rendered on next page without page-break-inside: avoid

### ISSUE THREAD

**Issue by tjmeneses** [dompdf/dompdf#1651]
Repro code at the bottom. When a list e.g. `<ul>` has exactly enough lines to reach the bottom of the current page, the entire list is rendered on the next page as if `page-break-inside: avoid` or `page-break-before: always` was set. If it's 1+ lines longer (e.g. `$li < 46`), the additional `<li>`s page break as expected. One workaround I found is to include `&nbsp;` after the `</ul>`.

CSS file
```css
html {
	font-size: 16px;
}
body {
	margin: 200px;
	padding: 0;
	font-family: Helvetica, Calibri;
	font-size: 1.75rem;
	background-color: red;
}
ul {
	padding-left: 15%;
	margin: 0;
	page-break-inside: auto;
}
```
PHP file, <body> content
```php
<div style="background-color: lightblue;">
	<p style="background-color: yellow;">hi</p>
	<ul style="background-color: orange;">
		<?php for ($li=1; $li < 45; $li++): ?>
			<li><?=$li?></li>
		<?php endfor ?>
	</ul>
	<!-- <span>&nbsp;</span> -->
</div>
```
