### ISSUE TITLE
What causes this table rendering issue?

### ISSUE THREAD

**Issue by sandervanhooft** [dompdf/dompdf#1715]
Hi,

This seems to be rendered just nicely in html, but not while using dompdf ([see debugger here](http://eclecticgeek.com/dompdf/debug.php?identifier=fd38feb807975b0ce5853f0a9504ac99)).

I have tried different solutions, searched here and on StackOverflow, but can't find a solution. The html is validated on W3C.

Any suggestions on how to fix this?

Sander

**Comment by sandervanhooft** [comment]
I narrowed the problem down to [this line](https://github.com/sparksuite/simple-html-invoice-template/blob/master/invoice.html#L22):

``` CSS
    .invoice-box table {
        width: 100%;
        line-height: inherit; /* REMOVE THIS LINE */
        text-align: left;
    }
```
That fixes it.
