### ISSUE TITLE
CSS variables

### ISSUE THREAD

**Issue by caliburn82** [dompdf/dompdf#1872]
I get problems when using CSS variables on margin or padding.

```css
:root {
    --spacing: 20px;
    --size: 300px;
    --grey: #888888;
}

.container {
    background: var(--grey-d);
    font-size: var(--spacing);
    margin: var(--spacing) 0; /* Errors: A non-numeric value encountered */
    padding: var(--spacing); /* Error: Box property calculation requires containing block width */
    width: var(--size);
}
```
I've been informed that dompdf doesn't support css variables, but would it be possible to add this to future revisions?

In the short term however, could error handling be added when variables are encounterd?
