### ISSUE TITLE
Trouble aligning children to bottom

### ISSUE THREAD

**Issue by resident0** [dompdf/dompdf#1961]
I'm trying to display a bar graph using multi colored ` div `s in a table. The problem is that table cell content doesn't align to the bottom of the cell.
HTML:
Notes: 
  - There are no spaces in the cell content because white space is respected by inline elements.
  - ` .barContainer `  ` height ` is styled inline because it is configurable.
  - All other heights are calculated when the table is created.
  - ` margin-left ` on each  ` .bar0 ` is styled inline because ` text-align: center ` appears to only affect text nodes (potentially a separate issue).
     This is calculated when the table is created.
```html 
    <table class="bargraph">
      <tr class="graphBody">
        <td class="barContainer" style="height:12.5rem;"><div class="bar0" title="$145.20" style="height: 1.2305084745763rem; margin-left: 11.5%;"></div><div class="gap"></div><div class="bar1" title="$577.74" style="height: 4.8961016949153rem;"></div><div class="gap"></div><div class="bar2" title="$1,475" style="height: 12.5rem;"></div><div class="gap"></div><div class="bar3" title="$135" style="height: 1.1440677966102rem;"></div><div class="gap"></div><div class="bar4" title="$639.84" style="height: 5.4223728813559rem;"></div><div class="gap"></div><div class="bar5" title="$109.12" style="height: 0.92474576271186rem;"></div></td>
        <td class="space"></td>
        <td class="barContainer" style="height:12.5rem;"><div class="bar0" title="$145" style="height: 1.228813559322rem; margin-left: 11.5%;"></div><div class="gap"></div><div class="bar1" title="$559" style="height: 4.7372881355932rem;"></div><div class="gap"></div><div class="bar2" title="$1,475" style="height: 12.5rem;"></div><div class="gap"></div><div class="bar3" title="$135" style="height: 1.1440677966102rem;"></div><div class="gap"></div><div class="bar4" title="$0" style="height: 0rem;"></div><div class="gap"></div><div class="bar5" title="$82" style="height: 0.69491525423729rem;"></div></td>
        <td class="space"></td>
        <td class="barContainer" style="height:12.5rem;"><div class="bar0" title="$0" style="height: 0rem; margin-left: 11.5%;"></div><div class="gap"></div><div class="bar1" title="$18.72" style="height: 0.15864406779661rem;"></div><div class="gap"></div><div class="bar2" title="$0" style="height: 0rem;"></div><div class="gap"></div><div class="bar3" title="$0" style="height: 0rem;"></div><div class="gap"></div><div class="bar4" title="$639.84" style="height: 5.4223728813559rem;"></div><div class="gap"></div><div class="bar5" title="$27.28" style="height: 0.23118644067797rem;"></div></td>
        <td class="space"></td>
        <td class="barContainer" style="height:12.5rem;"><div class="bar0" title="$0" style="height: 0rem; margin-left: 11.5%;"></div><div class="gap"></div><div class="bar1" title="$0" style="height: 0rem;"></div><div class="gap"></div><div class="bar2" title="$0" style="height: 0rem;"></div><div class="gap"></div><div class="bar3" title="$0" style="height: 0rem;"></div><div class="gap"></div><div class="bar4" title="$528" style="height: 4.4745762711864rem;"></div><div class="gap"></div><div class="bar5" title="$0" style="height: 0rem;"></div></td>
        <td class="space"></td>
        <td class="barContainer" style="height:12.5rem;"><div class="bar0" title="$0" style="height: 0rem; margin-left: 11.5%;"></div><div class="gap"></div><div class="bar1" title="$0" style="height: 0rem;"></div><div class="gap"></div><div class="bar2" title="$0" style="height: 0rem;"></div><div class="gap"></div><div class="bar3" title="$0" style="height: 0rem;"></div><div class="gap"></div><div class="bar4" title="$111.84" style="height: 0.94779661016949rem;"></div><div class="gap"></div><div class="bar5" title="$0" style="height: 0rem;"></div></td>
      </tr>
    </table>
```

CSS:

```css
@page {
  margin: 1rem 2rem;
  font-family: Garamond, serif;
}

table {
  border-collapse: collapse;
}

th {
  text-align: center;
}

.bargraph {
  margin: 1.25rem auto;
  page-break-after: always;
}

.graphBody {
  font-size: 1.2rem;
  background-color: #f4f4f4;
  /* overflow: hidden; */
}

.space {
  width: 0.25rem;
}

.barContainer {
  width: 5rem;
  padding: 0;
  background-color:#f4f4f4;
  border: 0.125rem solid #e1e1e1;
  border-bottom: none;
  border-top: none;
  /* vertical-align: bottom; */
}

.barContainer div {
  display: inline-block;
  width: 7%;
  /* vertical-align: bottom; */
}

.bar0 {
  background-color: #fe0000;
  display: inline-block;
}

.bar0Label {
  color: #fe0000;
}

.bar1 {
  background-color: #0071bd;
  display: inline-block;
}

.bar1Label {
  color: #0071bd;
}

.bar2 {
  background-color: #cf5300;
  display: inline-block;
}

.bar2Label {
  color: #cf5300;
}

.bar3 {
  background-color: #ba9907;
  display: inline-block;
}

.bar3Label {
  color: #ba9907;
}

.bar4 {
  background-color: #00ff01;
  display: inline-block;
}

.bar4Label {
  color: #00ff01;
}

.bar5 {
  background-color: #009345;
  display: inline-block;
}

.bar5Label {
  color: #009345;
}

.bar6 {
  background-color: #02066f;
  display: inline-block;
}

.bar6Label {
  color: #02066f;
}
```

The browser renders: 

![expected](https://user-images.githubusercontent.com/9022010/60598273-05c2dd00-9d72-11e9-8a64-9befb33596e3.png)

dompdf renders:

![NoValign](https://user-images.githubusercontent.com/9022010/60599517-386dd500-9d74-11e9-85e1-2a3c4c277b34.png)

If ` vertical-align: bottom; ` is applied to` td `s:

![tdValign](https://user-images.githubusercontent.com/9022010/60599663-77038f80-9d74-11e9-8205-8e4711e798fe.png)

if ` vertical-align: bottom; ` is applied to ` div `s:

![divValign](https://user-images.githubusercontent.com/9022010/60599754-9b5f6c00-9d74-11e9-8958-58c6178ad457.png)

if ` vertical-align: bottom; ` is applied to ` td `s and ` div `s:

![tdDivValign](https://user-images.githubusercontent.com/9022010/60600657-2db43f80-9d76-11e9-98ae-00aa6c924746.png)

if ` vertical-align: bottom; ` is not applied and ` margin-top `  is added, calculated not to exceed the height of ` .barContainer ` as suggested in issue #672 :

![topMargin](https://user-images.githubusercontent.com/9022010/60600742-605e3800-9d76-11e9-9533-14318e9211f8.png)

I tried changing the table elements to ` div `s and the alignment issue persisted.

If there's a workaround that I overlooked or haven't thought of I would appreciate some direction.

Thank you for taking the time to look this over.
