### ISSUE TITLE
CPDF breaks when remote fonts served via intermediate script (e.g. PHP) due to incorrect local file extension

### ISSUE THREAD

**Issue by MarkMaldaba** [dompdf/dompdf#1976]
I've recently upgraded from DomPDF 0.6.2 to 0.8.3 and have found that a custom font we were using is now being rendered incorrectly.  I have managed to locate a version of DomPDF 0.7.0 and the font rendered OK in that version, too, therefore the issue arose between 0.7.0 and 0.8.3 (probably, 0.8.0, but due to issue #1975 I couldn't test this).

Here is an image demonstrating the problem:

> ![Font issue in DomPDF 8 0](https://user-images.githubusercontent.com/1492120/62857199-e8791b00-bcee-11e9-801a-c346f11c6b37.png)

(Ignore the fact that 'normal text' is rendering in the same font in all cases - that is a separate and unrelated issue.)

Here is the HTML used to generate the above document:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>DomPDF Font Test</title>

	<link rel="stylesheet" type="text/css" href="http://localhost/fonts/mangerica/stylesheet.css">
	<style type="text/css">
		.Styled {
			font-family: Mangerica;
		}
	</style>
</head>
<body>

	Normal text<br>
	<div class="Styled">
		Normal text using Mangerica<br>
	</div>

	<hr>

	<b>Bold text</b><br>
	<div class="Styled">
		<b>Bold text using Mangerica</b><br>
	</div>

	<hr>

	<i>Italic text</i><br>
	<div class="Styled">
		<i>Italic text using Mangerica</i><br>
	</div>

	<hr>

	<b><i>Bold-Italic text</b></i><br>
	<div class="Styled">
		<b><i>Bold-Italic text using Mangerica</b></i><br>
	</div>

</body>
</html>
```

And here is the CSS in the linked file, `http://localhost/fonts/mangerica/stylesheet.css`:
```css
/* Regular */
@font-face {
    font-family: 'Mangerica';
    src: url('Mangerica-Light.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

/* Italic */
@font-face {
    font-family: 'Mangerica';
    src: url('Mangerica-LightItalic.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
}

/* Bold */
@font-face {
    font-family: 'Mangerica';
    src: url('Mangerica-SemiBold.ttf') format('truetype');
    font-weight: bold;
    font-style: normal;
}

/* Bold Italic */
@font-face {
    font-family: 'Mangerica';
    src: url('Mangerica-SemiBoldItalic.ttf') format('truetype');
    font-weight: bold;
    font-style: italic;
}
```

Observations:

* I can see, with verbose logging enabled, that the font files are fetched, that the cache files are created in `dompdf/lib/fonts/` and that the fonts are listed in `dompdf_font_family_cache.php`, so there is no issue with the fonts being located/loaded.
* The above tests were generated with a clean cache each time.
* However, I found that if I ran it under 0.7.0, which worked, and then switched to 0.8.3 *without clearing the cache* then the font rendered OK.  Therefore it looks like it is part of the code which builds the font cache files that is causing the problem.

I will continue to experiment and will post back any further observations.  I will see if I can narrow it down to a specific location in the code.
