### ISSUE TITLE
Watermarking Problem

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#208]
_Original author: abhijit....@gmail.com (November 26, 2010 12:01:29)_

Hi,

I am using DOM PDF library to create PDF files in my application. It is working perfectly in my localhost but in server background image is not coming. The library is exactly same. I have checked the image path that is perfectly alright. If I use this image in other place then it is coming but on background it is not coming.

I have also consult with my server administrator regarding this the configuration are identical in localhost and server

I adding the CSS like this

``` css
 body{
        font-family:Arial, Helvetica, sans-serif;
        margin:0px;
        padding:0px;
        text-align:center;
        background:url('. $_SERVER['DOCUMENT_ROOT'].'images/front/padf_back.gif);
        background-repeat:no-repeat;
        background-position:center;
        }
```

any one can help me to solve this problem

with regards,
Abhijit

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=202_
