### ISSUE TITLE
&nbsp; is not displayed correctly when using a custom font

### ISSUE THREAD

**Issue by keulinho** [dompdf/dompdf#2445]
`&nbsp;` character is not displayed correctly when using a custom google font

# How to reproduce
```html
<!DOCTYPE html>
<html>
<head>

    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&display=swap" rel="stylesheet">

    <style type="text/css">
        body {
            font-family: 'Source Sans Pro', sans-serif;
            font-size: 12px;
            line-height: 12px;
            width: 100%;
        }
    </style>
</head>

<body>
<h1>123&nbsp;€</h1>
</body>
</html>
```

# Result
![image](https://user-images.githubusercontent.com/15930605/116671832-b4053100-a9a1-11eb-80c6-395559c66d0a.png)

# Expected Result
The space should be displayed correctly.

# Affected versions
Only versions > 0.8.5 are affected, it worked before.

Additionally it works without the custom font.

**Comment by bsweeney** [comment]
We have seen some corruption of this type with other fonts. I'm seeing it in my test bed using versions as low as 0.8.4. I believe a temporary work-around, at the cost of PDF size, is to disable font subsetting. Which may indicate the issue is with php-font-lib instead of Dompdf, but a bit more research is in order to definitively identify the source.

**Comment by simonschaufi** [comment]
I have the same problem and can confirm it since upgrading from 0.8.5 to any higher version. 

I embedded the font like so:

```css
@font-face {
            font-family: 'IB';
            font-weight: normal;
            font-style: normal;
            src: url('/path/to/font.ttf') format('truetype');
 }
```

and each `&nbsp` is replaced by something hat looks like `fi`
