### ISSUE TITLE
Page Breaks not working as intended?

### ISSUE THREAD

**Issue by liam-milbel** [dompdf/dompdf#2469]
If I have any content that won't fit on the page, it will automatically flow to the next page, however, there's a problem with that. It causes problems with elements like tables.

![image](https://user-images.githubusercontent.com/84058589/120591997-6ab46f80-c480-11eb-9f55-d15a2e620913.png)

On the contrary, if I manually set a `page-break-before: always` on the element, it works as it should.

![image](https://user-images.githubusercontent.com/84058589/120592048-8750a780-c480-11eb-9f87-cab1b742381f.png)

As my content is dynamic, I cannot apply the page break CSS. I believe that the way content flows over to the next page is broken and is in need of fixing. When content automatically flows to a new page, it should behave as if the page break CSS was used.

**Comment by bsweeney** [comment]
We would need to see a sample of the HTML + CSS to know what's going on here.

**Comment by liam-milbel** [comment]
This is the bulk of it. Two of those will fit on a page just fine but a third flows and causes what you see in the first image.

```html
<div class="page-break-inside-1 mb-4">
    <table class="layout w-100">
        <tr>
            <td class="align-top">
                <img src="..." class="border-2 border-solid border-primary" style="border-radius: 139px;" />
            </td>
            <td>
                Lorem ipsum dolor sit amet...
            </td>
        </tr>
    </table>
</div>
```

```scss
table.layout {
    tr th,
    tr td {
        padding: 16px;
        &:first-child {
            padding-left: 0;
        }
        &:last-child {
            padding-right: 0;
        }
    }
}

.page-break-inside-1 {
    page-break-inside: avoid;
    break-inside: avoid;
}
```

Surround all of that with the following:
```html
<body>
    <main>
        <section>
            <!-- section content goes here -->
        </section>
    </main>
</body>
```
