### ISSUE TITLE
Table border top and bottom does not work properly

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#266]
_Original author: ukarr...@gmail.com (April 05, 2011 07:45:27)_

<b>What steps will reproduce the problem?</b>
1. Design a table with several columns, with thead and tbody tag
2. Style it with CSS (see below) and use border-top and border-bottom
3. Generate PDF

<b>What is the expected output? What do you see instead?</b>
The border has to be as long as the whole table (one cell at the end is missing). And the border bottom (at the bottom of the thead) is missing as well.

<b>What version of the product are you using? On what operating system?</b>
dompdf_0-6-0_beta2.zip
SUSE Linux Enterprise Server 10 SP3 (x86_64)
PHP 5.2.14

<b>Please provide any additional information below.</b>
Maybe there is a correlation to those bugs:
#235
#258

Here the CSS:

``` css
table {
border-bottom: 2px solid #888888;
border-collapse: collapse;
border-top: 2px solid #888888;
margin-bottom: 0.5em;
margin-top: 0.5em;
width: auto;
}

thead th {
border-bottom: 2px solid #880000;
color: #111111;
}

tbody th {
border-bottom: 1px solid #FFFFFF;
text-align: left;
}

tbody th {
background: none repeat scroll 0 0 #E6E6E6;
color: #333333;
}
```

Here the HTML Code (I changed the content in it):

``` html
<table class="tbl_class" style="font-size: 0.95em;">
<thead style="vertical-align: bottom;">
<tr><th colspan="4">a</th>
<th colspan="1">b</th>
</tr>
<tr>
<th style="width: 5%;">1</th>
<th style="border-right: 1px solid #000000; width: 5%;">2</th>
</tr>
</thead>

<tbody>
  <tr>
<th>foo</th>
<td>bar</td>

<td>+</td>

</tr>
</tbody>
</table>
```

_Attached Files:_
table_error.png - shows the error
table_proper.png - shows the proper table in HTML

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=260_
