### ISSUE TITLE
Want to set different background color on full body !!

### ISSUE THREAD

**Issue by Ok9xNirab** [dompdf/dompdf#2938]
### Screenshot :

![preview](https://i.ibb.co/jG5wkW2/Screenshot-2022-06-29-at-1-59-09-PM.png)

### CSS

```css
@page {
   /* using padding , still same output */
    margin: 1cm 2cm 3cm;
    background-color: #f1f1ee;
}

* {
    line-height: 1.5em;
}

body {
    background-color: #f1f1ee;
    color: #111111;
    margin: 0cm;
    line-height: 1.3rem;
}
```

**Thanks**
