### ISSUE TITLE
Проблема с background-image

### ISSUE THREAD

**Issue by maloyza** [dompdf/dompdf#3241]
У меня проект на Laravel 10, я использую библиотеку dompdf для генерации pdf-файла с html.
В html у меня есть таблица, для thead, мне необходимо сделать градиентный фон. Но linear-gradient не поддерживается библиотекой. Поэтому я хочу поставить хочу поставить картинку на задний фон. Я прописал задний фон таким образом:

Но по какой-то причине, в сгенерированном файле pdf, задний фон дублируется на 2 th, вместо того что бы растягиваться на весь thead. Подскажите в чем проблема.
```css
thead {
            background: url('storage/assets/cp/table-info-bar.png') no-repeat center center fixed;
            background-size: 100% 100%;
}
``` 

```html
<table class="table-info">
                <thead class='table-head-info'>
                    <tr class="row">
                        <th class="first-column-info">LS-HE09KDE2/LU-HE09KDE2</th>
                        <th class="second-column-info">LS-HE12KDE2/LU-HE12KDE2</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
``` 

Вот так выглядит в обычном виде
![image](https://github.com/dompdf/dompdf/assets/109759619/0b95fb3a-e24b-4f78-a8db-cb4f7c2f9011)

А вот так в pdf
![image](https://github.com/dompdf/dompdf/assets/109759619/0fff0c1a-7bcf-4dd9-9852-84f6cc4b16a4)
