### ISSUE TITLE
@page is not recognized unless it is followed by a space

### ISSUE THREAD

**Issue by bsweeney** [dompdf/dompdf#614]
The current regex used in parsing the document styles requires a space after the `@page` rule declaration. When the space is missing the rule declaration is ignored.

e.g. the following rule will not be applied:

``` css
@page{margin:0px;}
```

while this rule will be parsed:

``` css
@page {margin:0px;}
```
