### ISSUE TITLE
First page doesn't show footer when document has 2 or more pages?

### ISSUE THREAD

**Issue by rk** [dompdf/dompdf#688]
I'm generating a PDF report for internal use. Because I have no direct control over how large that report can be, I've set page numbers just in case a client prints the report. The weird thing is, when the report is more than 1 page the first page doesn't show its footer. However, the page counter picks up correctly at "Page 2" on the proper page. But a single-page document works just fine.

I'm using the latest copy of DOMPDF on GitHub.

``` scss
/* This is the sass source of the print stylesheet */

@page {
    margin: 0.35in 0.75in;
}

body {
    font-family: 12pt/16pt 'DejaVu Sans', serif;
    color: #222;
    margin: 0.3in 0;
    padding: 0.1in 0;
    border-top: 0.5pt solid #aaa;
    border-bottom: 0.5pt solid #aaa;
}

/* ... clipped header styles, etc ... */

#header, #footer {
    position: fixed;
    left: 0;
    right: 0;
    color: #999;
    font: 10pt/12pt 'DejaVu Sans';
    font-size: 10pt;
    line-height: 12pt;
    z-index: 5;
}

#header {
    top: 0;

    border-collapse: collapse;

    tr {
        background: transparent;
    }

    td {
        border: 0;
    }
}

#footer {
    bottom: 0.2in;
    text-align: center;
}

.page-number:before {
    content: "Page " counter(page);
    white-space: nowrap;
}
```
