### ISSUE TITLE
Footers repeating

### ISSUE THREAD

**Issue by Spreeuw** [dompdf/dompdf#746]
I'm creating a document with several pages (actually sections, since it could be more than one page with 1 footer at the end of the section). Each section has it's own footer (each of it slightly different), which properly floats to the end of that section when I put it in a single document.

However, when I combine multiple of these sections into 1 document, the footers are repeated on every page, stacking them on top of eachother page by page (ending up with a mess at the last page).

I am positioning the footer with position: fixed

``` css
.foot {
  position: fixed;
  bottom: 0;
  margin-bottom: 0;
  left: 0;
  right: 0;
  height: 9cm;
  text-align: center;
}
```

Is this a bug or am I doing something wrong? Strictly speaking what I want is probably not a footer (like with page numbering) but a div at the bottom of the current page, if that's of any help.
