### ISSUE TITLE
CSS or HTML solution for dot leaders

### ISSUE THREAD

**Issue by benjibee** [dompdf/dompdf#770]
[Dot leaders](http://printwiki.org/Dot_Leaders) are most mostly used in print for restaurant menus or table of content listings. From what I gather, both of these are commonly distributed as PDFs, and very often auto-generated by software such as _dompdf_.

The W3C has had [a draft spec on this](http://www.w3.org/TR/css3-gcpm/) function for about a decade, but seem to be dragging their feet about any actual implementation. Though, they do provide [some examples of workarounds](http://www.w3.org/Style/Examples/007/leaders.en.html).

Also, [this A List Apart article](http://alistapart.com/article/building-books-with-css3#section6) talks about this very feature using [Prince](http://www.princexml.com/), who actually seem to have gone ahead and made [their own function](http://www.princexml.com/doc/8.1/properties/content/) years ago.

Using the following code produces great results for the web, across all browsers and mobile, even for my email template, but not luck so far with dompdf. I'm guessing most of the trouble is with the current `float` support.

``` css
        ul.leaders {
            max-width: 30em;
            padding: 0;
            overflow-x: hidden;
            list-style: none
        }
        ul.leaders li:after {
            float: left;
            width: 0;
            white-space: nowrap;
            content: ". . . . . . . . . . . . . . . . . . . . "
                     ". . . . . . . . . . . . . . . . . . . . "
                     ". . . . . . . . . . . . . . . . . . . . "
                     ". . . . . . . . . . . . . . . . . . . . "
        }
        ul.leaders span:first-child {
            padding-right: 0.33em;
            background: white
        }
        ul.leaders span + span {
            float: right;
            padding-left: 0.33em;
            background: white;
            position: relative;
            z-index: 1
        }
        .seperator:after {
            content: "" !important;
        }
```

Below are two examples of the different results of this code:

> ![Web screenshot of dot leaders per W3C example](https://f.cloud.github.com/assets/620119/1975973/61b0160e-8384-11e3-8be7-c2feb54a3562.png)

_Screenshot of dot leaders per W3C example in Chrome_

> ![*Screenshot of same code, rendered by dompdf](https://f.cloud.github.com/assets/620119/1975999/ce1b29c8-8384-11e3-951f-29c45ca5888e.png)

_Screenshot of same code, rendered by dompdf_

Any recommendations on how this could be achieved would be _very_ much appreciated!
