### ISSUE TITLE
Bootstrap Glyphicons breaks Dompdf

### ISSUE THREAD

**Issue by johndekroon** [dompdf/dompdf#860]
Hi,

It seems that the glyphicons that are included in Twitter Bootstrap (3.2.0) put Dompdf on it's knees. The following line of CSS is the problem, when I remove it, Dompdf does it's job:

``` css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('/fonts/glyphicons-halflings-regular.eot');
  src: url('/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('/fonts/glyphicons-halflings-regular.woff') format('woff'), url('/fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

(line 263 in the default compiled version)
