### ISSUE TITLE
Support for @font-face unicode-range

### ISSUE THREAD

**Issue by NateWr** [dompdf/dompdf#913]
I'd like to use Google's [Noto](https://www.google.com/get/noto/) fonts to improve language compatibility in my PDF exports. This would be part of software that would get run on lots of different servers over which I can't control what fonts are installed or not.

Here's how I've attempted to declare my fonts with `@font-face`:

```

@font-face {
	font-family: 'Noto Sans';
	font-style: normal;
	font-weight: normal;
	src: local('Noto Sans'), local('NotoSans'),	url(http://full/path/to/fonts/NotoSans-Regular.ttf) format('truetype');
	unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
@font-face {
	font-family: 'Noto Sans';
	font-style: normal;
	font-weight: normal;
	src: local('Noto Sans Arabic'), local('NotoSansArabic'),	url(http://full/path/to/fonts/NotoNaskhArabic-Regular.ttf) format('truetype');
	unicode-range: U+060x-06Fx;
}
```

But this doesn't seem to be working. Arabic characters won't get displayed. And if I try to use a font stack to fall-back on a more workable font, it doesn't work:

```<p style="font-family: 'Noto Sans', sans-serif;">من</p>```

Is this a known issue? Or is there some way to get mixed-language documents that I'm missing? Thanks.

**Comment by bsweeney** [comment]
We have not coded in support for the `unicode-range` property yet. Until we've added support for this feature you'll need to configure two different fonts in your CSS then reference them in your document. Something like the following:

```css
@font-face {
    font-family: 'Noto Sans';
    font-style: normal;
    font-weight: normal;
    src: local('Noto Sans'), local('NotoSans'), url(http://full/path/to/fonts/NotoSans-Regular.ttf) format('truetype');
}
@font-face {
    font-family: 'Noto Sans Arabic';
    font-style: normal;
    font-weight: normal;
    src: local('Noto Sans Arabic'), local('NotoSansArabic'),    url(http://full/path/to/fonts/NotoNaskhArabic-Regular.ttf) format('truetype');
}
```

```html
<span style="Noto Sans, sans-serif;">blah</span> <span style="Noto Sans Arabic, Noto Sans, sans-serif;" lang="ar" dir="rtl">بلاه</span>
```
